config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
   member do
   get :following, :followers
   end
  end
  resources :todolists
  resources :relationships, only: [:create, :destroy]
  resources :qalists
  resources :comments
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @todolist = current_user.todolists.build if logged_in?
    @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc) if logged_in?
    @latest_items = current_user.latest_items.order(created_at: :desc).limit(1) if logged_in?
    @qalist = current_user.qalists.build if logged_in?
    @latest_qalists = current_user.latest_qalists.order(created_at: :desc).limit(1) if logged_in?
    @feed_qalists = current_user.feed_qalists.includes(:user).order(created_at: :desc) if logged_in?
    @comment = current_user.comments.build if logged_in?
  end
  
end

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
  </div>
  
  <div>
  <ul class="nav nav-tabs" role="tablist">
    <li class="active" role="presentation">
      <a aria-controls="tab_a" data-toggle="tab" href="#tab_a" role="tab">最近作ったリスト</a>
    </li>
    <li role="presentation" class="dropdown">
      <a href="#" class="dropdown-toggle" id="myTabDrop2" data-toggle="dropdown" aria-controls="myTabDrop2-contents" aria-expanded="false">タイムライン<span class="caret"></span></a> 
       <ul class="dropdown-menu" aria-labelledby="myTabDrop2" id="myTabDrop2-contents"> 
        <li class=""><a href="#dropdown3" role="tab" id="dropdown3-tab" data-toggle="tab" aria-controls="dropdown3" aria-expanded="false">チェックリスト</a></li> 
        <li class=""><a href="#dropdown4" role="tab" id="dropdown4-tab" data-toggle="tab" aria-controls="dropdown4" aria-expanded="false">Q&Aリスト</a></li> 
       </ul> 
    </li>
    <li role="presentation" class="dropdown">
      <a href="#" class="dropdown-toggle" id="myTabDrop1" data-toggle="dropdown" aria-controls="myTabDrop1-contents" aria-expanded="false">リスト作成<span class="caret"></span></a> 
       <ul class="dropdown-menu" aria-labelledby="myTabDrop1" id="myTabDrop1-contents"> 
        <li class=""><a href="#dropdown1" role="tab" id="dropdown1-tab" data-toggle="tab" aria-controls="dropdown1" aria-expanded="false">チェックリスト(承認者付き)</a></li> 
        <li class=""><a href="#dropdown2" role="tab" id="dropdown2-tab" data-toggle="tab" aria-controls="dropdown2" aria-expanded="false">Q&Aリスト</a></li> 
       </ul> 
    </li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tab_a" role="tabpanel">
     <div class="col-md-12">
      <h3>最近作ったリスト</h3>
       <%= render 'shared/latest' %>
     </div>
    </div>
    <div class="tab-pane active" id="tab_a" role="tabpanel">
     <div class="col-md-12">
      <h3>最近作ったQ&Aリスト</h3>
       <%= render 'shared/latest_qalist' %>
     </div>
    </div>
    
    <div class="tab-pane fade" id="dropdown3" role="tabpanel" aria-labelledby="dropdown3-tab">
     <div class="col-md-12">
      <h3>Todolist Feed</h3>
       <%= render 'shared/feed' %>
     </div>
    </div>
    
    <div class="tab-pane fade" id="dropdown4" role="tabpanel" aria-labelledby="dropdown4-tab">
     <div class="col-md-12">
      <h3>Q&Alist Feed</h3>
       <%= render 'shared/feed_qalist' %>
     </div>
    </div>
    
    
    <div class="tab-pane fade" role="tabpanel" id="dropdown1" aria-labelledby="dropdown1-tab">
      <aside class="class= col-md-12">
       <section class="user_info">
        <%= render 'shared/user_info' %>
       </section>
       <section class="stats">
             <%= render 'shared/stats' %>
       </section>
       <section class="micropost_form">
        <%= render 'shared/todolist_form' %>
       </section>
      </aside>
    </div>
    
    <div class="tab-pane fade" role="tabpanel" id="dropdown2" aria-labelledby="dropdown2-tab">
      <aside class="class= col-md-12">
       <section class="user_info">
        <%= render 'shared/user_info' %>
       </section>
       <section class="stats">
             <%= render 'shared/stats' %>
       </section>
       <section class="micropost_form">
        <%= render 'shared/qalist_form' %>
       </section>
      </aside>
    </div>
    
  </div>
</div>
  
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the todolist</h1>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>