config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
   member do
   get :following, :followers
   end
  end
  resources :todolists
  resources :relationships, only: [:create, :destroy]
  resources :qalists
  resources :comments
end

app/views/shared/_comment_form.html.erb
<%= form_for(@comment) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new comment..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="todolists">
    <%= render @feed_items %>
  </ol>
<% end %>

app/views/shared/_feed_qalist.html.erb
<% if @feed_qalists.any? %>
  <ol class="todolists">
    <%= render @feed_qalists %>
  </ol>
<% end %>

app/views/shared/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>
      
      <%= f.label :birthday %>
      <%= f.date_select :birthday, start_year: 1950, end_year: 2016 %>

      <%= f.label :gender %>
      <%= f.select :gender, User.genders.keys, class: 'form-control' %>


      <%= f.label :location %>
      <%= f.text_field :location, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_latest.html.erb
<% if @latest_items != nil %>
  <ol class="todolists">
    <%= render @latest_items %>
  </ol>
<% end %>
  

app/views/shared/_latest_qalist.html.erb
<% if @latest_qalists != nil %>
  <ol class="todolists">
    <%= render @latest_qalists %>
  </ol>
<% end %>
  

app/views/shared/_qalist_form.html.erb
<%= form_for(@qalist, html:{class: 'form-horizontal'}) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
  <div class="field">
   <div class="panel-group" role="tablist"> 
   <div class="panel panel-default"> 
     <table class="table table-striped table-bordered table-hover">
          <tbody>
             <tr>
               <th colspan="3">リストタイトル</th>
            </tr>
            <td colspan="3"><%= f.text_field :title, class: 'form-control' %></td>
            <tr>
               <th colspan="3">質問の回答者(メールアドレス)</th>
            </tr>
            <td colspan="3"><%= f.text_field :answer, class: 'form-control' %></td>
            <tr>
               <th></th>
               <th>質問</th>
               <th>回答期限</th>
            </tr>
            <tr>
                <td>1</td>
                <td><%= f.text_field :query0, class: 'form-control' %></td>
                <td><%= f.text_field :line0, class: 'form-control' %></td>
                    <%= f.hidden_field :tdnumber0 %>
            </tr>
            <tr>
                <td>2</td>
                <td><%= f.text_field :query1, class: 'form-control' %></td>
                <td><%= f.text_field :line1, class: 'form-control' %></td>
                    <%= f.hidden_field :tdnumber1 %>          
            </tr>
            
            <tr>
                <td>3</td>
                <td><%= f.text_field :query2, class: 'form-control' %></td>
                <td><%= f.text_field :line2, class: 'form-control' %></td>
                    <%= f.hidden_field :tdnumber2 %>          
            </tr>

            <tr>
                <td>4</td>
                <td><%= f.text_field :query3, class: 'form-control' %></td>
                <td><%= f.text_field :line3, class: 'form-control' %></td>
                    <%= f.hidden_field :tdnumber3 %>          
            </tr>
            
            <tr>
                <td>5</td>
                <td><%= f.text_field :query4, class: 'form-control' %></td>
                <td><%= f.text_field :line4, class: 'form-control' %></td>
                    <%= f.hidden_field :tdnumber4 %>          
            </tr>

          </tbody>
       </table>
       </div> 
     </div> 
       
     <div class="panel-group" role="tablist"> 
      <div class="panel panel-default"> 
       <div class="panel-heading" role="tab" id="collapseListGroupHeading1"> 
        <h4 class="panel-title"> 
         <a href="#collapseListGroup1" class="collapsed" role="button" data-toggle="collapse" aria-expanded="false" aria-controls="collapseListGroup1"> +質問を追加する </a> 
        </h4> 
       </div> 
        <div class="panel-collapse collapse" role="tabpanel" id="collapseListGroup1" aria-labelledby="collapseListGroupHeading1" aria-expanded="false" style="height: 0px;"> 
         <table class="table table-striped table-bordered table-hover">
          <tbody>
             
               <th></th>
               <th>質問</th>
               <th>回答期限</th>
            </tr>
            <tr>
                <td>6</td>
                <td><%= f.text_field :query5, class: 'form-control' %></td>
                <td><%= f.text_field :line5, class: 'form-control' %></td>
                    <%= f.hidden_field :tdnumber5 %>
            </tr>
             <tr>
                <td>7</td>
                <td><%= f.text_field :query6, class: 'form-control' %></td>
                <td><%= f.text_field :line6, class: 'form-control' %></td>
                    <%= f.hidden_field :tdnumber6 %>          
            </tr>
            
            <tr>
                <td>8</td>
                <td><%= f.text_field :query7, class: 'form-control' %></td>
                <td><%= f.text_field :line7, class: 'form-control' %></td>
                    <%= f.hidden_field :tdnumber7 %>          
            </tr>

            <tr>
                <td>9</td>
                <td><%= f.text_field :query8, class: 'form-control' %></td>
                <td><%= f.text_field :line8, class: 'form-control' %></td>
                    <%= f.hidden_field :tdnumber8 %>          
            </tr>
            
            <tr>
                <td>10</td>
                <td><%= f.text_field :query9, class: 'form-control' %></td>
                <td><%= f.text_field :line9, class: 'form-control' %></td>
                    <%= f.hidden_field :tdnumber9 %>          
            </tr>

          </tbody>
       </table>
        </div> 
      </div> 
     </div>  

  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
    <a href="<%= following_user_path(@user) %>">
      <strong id="following" class="stat">    
        <%= @user.following_relationships.count %>
      </strong>
      following
    </a>
    <a href="<%= followers_user_path(@user) %>">
        <strong id="followers" class="stat">
            <%= @user.follower_relationships.count %>
        </strong>
        followers
    </a>
</div>

app/views/shared/_todolist_form.html.erb
<%= form_for(@todolist, html:{class: 'form-horizontal'}) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
  <div class="field">

     <table class="table table-striped table-bordered table-hover">
          <tbody>
             <tr>
               <th colspan="3">リストタイトル</th>
            </tr>
            <td colspan="3"><%= f.text_field :title, class: 'form-control' %></td>
            <tr>
               <th colspan="3">承認者(メールアドレス)</th>
            </tr>
            <td colspan="3"><%= f.text_field :approver, class: 'form-control' %></td>
            <tr>
               <th>やること</th>
               <th>期日</th>
               <th>Action</th>
            </tr>
            <tr>
                <td><%= f.text_field :things, class: 'form-control' %></td>
                <td><%= f.text_field :note, class: 'form-control' %></td>
                <% f.select :situation, Todolist.situations.keys %>
                <% f.select :status, Todolist.statuses.keys %>
                <td></td>             
            </tr>
            <%= f.nested_fields_for :listtables, wrapper_tag: :tr do |q| %>
                <td><%= q.text_field :things, class: 'form-control' %></td>
                <td><%= q.text_field :note, class: 'form-control' %></td>
                <% q.select :situation, Listtable.situations.keys %>
                <% q.select :status, Listtable.statuses.keys %>
                <td><%= q.remove_nested_fields_link 'Delete', class: 'btn btn-danger', role: 'button' %></td>
            <% end %>

          </tbody>
       </table>
      <%= f.add_nested_fields_link :listtables, 'Add new table', class: 'btn btn-primary', role: 'button' %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.todolists.count, "todolist") %></span>