config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users do
   member do
   get :following, :followers
   end
  end
  resources :todolists
  resources :relationships, only: [:create, :destroy]
  resources :qalists
  resources :comments
end

app/models/qalist.rb
class Qalist < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :answer, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
  has_many :comments, class_name: "Comment",  foreign_key: "qalist_id", dependent: :destroy
  has_many :commented_qalists, through: :comments, source: :qalist
  
  def answered_comments
    Qalist.where(qalist_id: commented_qalists_ids + [self.id])
  end
  
end

app/controllers/qalists_controller.rb
class QalistsController < ApplicationController
 before_action :logged_in_user, only: [:create, :edit, :update, :show]

  def create
    @qalist = current_user.qalists.build(qalist_params)
    if @qalist.save
      flash[:success] = "Q&Alist created!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end
  
  def show
    @qalist = current_user.qalists.find_by(id: params[:id])
    if @qalist.nil?
      @qalist = Qalist.find(params[:id])
    end
    @user = current_user
    @comment = current_user.comments.build if logged_in?
    @comments = @user.comments.order(created_at: :desc)
    @answered_comments = Comment.where(answer_id: '@qalist.id', answer_td_id: '@qalist.line0').order(created_at: :desc) if logged_in?
    @answered_comments_1 = Comment.where(answer_id: '@qalist.id', answer_td_id_1: '@qalist.line1').order(created_at: :desc) if logged_in?
    @answered_comments_2 = Comment.where(answer_id: '@qalist.id', answer_td_id_2: '@qalist.line2').order(created_at: :desc) if logged_in?
    @answered_comments_3 = Comment.where(answer_id: '@qalist.id', answer_td_id_3: '@qalist.line3').order(created_at: :desc) if logged_in?
    @answered_comments_4 = Comment.where(answer_id: '@qalist.id', answer_td_id_4: '@qalist.line4').order(created_at: :desc) if logged_in?
    @answered_comments_5 = Comment.where(answer_id: '@qalist.id', answer_td_id_5: '@qalist.line5').order(created_at: :desc) if logged_in?
    @answered_comments_6 = Comment.where(answer_id: '@qalist.id', answer_td_id_6: '@qalist.line6').order(created_at: :desc) if logged_in?
    @answered_comments_7 = Comment.where(answer_id: '@qalist.id', answer_td_id_7: '@qalist.line7').order(created_at: :desc) if logged_in?
    @answered_comments_8 = Comment.where(answer_id: '@qalist.id', answer_td_id_8: '@qalist.line8').order(created_at: :desc) if logged_in?
    @answered_comments_9 = Comment.where(answer_id: '@qalist.id', answer_td_id_9: '@qalist.line9').order(created_at: :desc) if logged_in?
  end
  
  def destroy
    @qalist = current_user.qalists.find_by(id: params[:id])
    return redirect_to root_url if @qalist.nil?
    @qalist.destroy
    flash[:success] = "qalist deleted"
    redirect_to request.referrer || root_url
  end
  
  def edit
     @qalist = current_user.qalists.find_by(id: params[:id])
     @user = current_user
    if @qalist.nil?
      @qalist = Qalist.find(params[:id])
    end
  end
  
  def update
    @qalist = current_user.qalists.find_by(id: params[:id])
    if @qalist.nil?
      @qalist = Qalist.find(params[:id])
    end
    if @qalist.update_attributes(qalist_params)
      flash[:success] = "Q&Alist updated"
      @qalist.save
      redirect_to @qalist
    else
      render 'edit'
    end
  end
  
  private
  def qalist_params
    params.require(:qalist).permit(:title, :content, :answer, :query0, :line0, 
    :tdnumber0, :query1, :line1, :tdnumber1, :query2, :line2, :tdnumber2, 
    :query3, :line3, :tdnumber3, :query4, :line4, :tdnumber4, :query5, :line5, :tdnumber5, 
    :query6, :line6, :tdnumber6, :query7, :line7, :tdnumber7, :query8, :line8, :tdnumber8, 
    :query9, :line9, :tdnumber9)
  end
  
  def comment_params
    params.require(:comment).permit(:content, :answer_id, :answer_td_id, :answer_td_id_1, :answer_td_id_2,
     :answer_td_id_3,  :answer_td_id_4,  :answer_td_id_5,  :answer_td_id_6,  :answer_td_id_7,
     :answer_td_id_8,  :answer_td_id_9,)
  end
  
end

app/views/qalists/_qalist.html.erb
<li id="qalist-<%= qalist.id %>">
  <%= link_to gravatar_for(qalist.user, size: 50), qalist.user %>
  <span class="user"><%= link_to qalist.user.name, qalist.user %></span>
  <span class="title"><%= link_to qalist.title, qalist %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(qalist.created_at) %> ago.
    <% if current_user == qalist.user %>
      <%= link_to "delete", qalist, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

<table class="table table-striped table-bordered table-hover">
           
          <tbody>
          　<tr>
               <th>質問</th>
               <th>期日</th>
               <th>状況</th>
               <th>ステータス</th>
            </tr>
            <% if qalist.query0.present? %>
            <tr>
              <td><%= qalist.query0 %></td>
              <td><%= qalist.line0 %></td>
              <td></td>
              <td></td>
            </tr>
        　　<% end %>
        　　<% if qalist.query1.present? %>
            <tr>
              <td><%= qalist.query1 %></td>
              <td><%= qalist.line1 %></td>
              <td></td>
              <td></td>
            </tr>
        　　<% end %>
        　　<% if qalist.query2.present? %>
            <tr>
              <td><%= qalist.query2 %></td>
              <td><%= qalist.line2 %></td>
              <td></td>
              <td></td>
            </tr>
        　　<% end %>
        　　<% if qalist.query3.present? %>
            <tr>
              <td><%= qalist.query3 %></td>
              <td><%= qalist.line3 %></td>
              <td></td>
              <td></td>
            </tr>
        　　<% end %>
        　　<% if qalist.query4.present? %>
            <tr>
              <td><%= qalist.query4 %></td>
              <td><%= qalist.line4 %></td>
              <td></td>
              <td></td>
            </tr>
        　　<% end %>
        　　<% if qalist.query5.present? %>
            <tr>
              <td><%= qalist.query5 %></td>
              <td><%= qalist.line5 %></td>
              <td></td>
              <td></td>
            </tr>
        　　<% end %>
        　　<% if qalist.query6.present? %>
            <tr>
              <td><%= qalist.query6 %></td>
              <td><%= qalist.line6 %></td>
              <td></td>
              <td></td>
            </tr>
        　　<% end %>
        　　<% if qalist.query7.present? %>
            <tr>
              <td><%= qalist.query7 %></td>
              <td><%= qalist.line7 %></td>
              <td></td>
              <td></td>
            </tr>
        　　<% end %>
        　　<% if qalist.query8.present? %>
            <tr>
              <td><%= qalist.query8 %></td>
              <td><%= qalist.line8 %></td>
              <td></td>
              <td></td>
            </tr>
        　　<% end %>
        　　<% if qalist.query9.present? %>
            <tr>
              <td><%= qalist.query9 %></td>
              <td><%= qalist.line9 %></td>
              <td></td>
              <td></td>
            </tr>
        　　<% end %>
           </tbody>
</table>

app/views/qalists/_query0.html.erb
            <tr>
              <td><%= @qalist.query0 %></td>
              <td><%= @qalist.line0 %></td>
              <td></td>
              <td>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">回答する</button>
                 
                 <%= form_for(@comment) do |f| %>
                  <%= render 'shared/error_messages', object: f.object %>
                   
                   <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
                    
                    <div class="modal-dialog" role="document">
                     
                     <div class="modal-content">
                      
                      <div class="modal-header">
                       <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="exampleModalLabel">New message</h4>
                      </div>

                      <div class="modal-body">
                        <div class="form-group">
                          <label for="recipient-name" class="control-label">回答者</label>
                          <%= @user.name %>
                        </div>
          
                        <div class="form-group">
                         <label for="message-text" class="control-label">Message:</label>
                          <%= f.text_area :content, placeholder: "Compose new comment...", class: 'form-control', :size => "20x10" %>
                          <%= f.hidden_field :answer_id , :value => "@qalist.id" %>
                          <%= f.hidden_field :answer_td_id , :value => "@qalist.line0" %>
                        </div>
                    
                      </div>
                    
                      <div class="modal-footer">
                       <%= f.submit "Post", class: "btn btn-primary" %>
                      </div>
                   
                    </div>
                    
                  </div>
                  
               </div>
              <% end %>
            </td>
              
            <td>
              <% if @answered_comments.any? %>
               <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal0">Comments (<%= @answered_comments.count %>)</button>
                <div class="modal fade" id="myModal0" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                 <div class="modal-dialog" role="document">
                  <div class="modal-content">
                   <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                     <h4 class="modal-title" id="myModalLabel">コメント一覧</h4>
                   </div>
                    <div class="modal-body">
                     <ol class="comments">
                      <%= render partial: 'comments/comment', collection: @answered_comments %>
                     </ol>
                    </div>
                     <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                     </div>
                  </div>
                 </div>
               </div>
              <% end %>
            </td>
            </tr>

app/views/qalists/_query1.html.erb
            <tr>
              <td><%= @qalist.query1 %></td>
              <td><%= @qalist.line1 %></td>
              <td></td>
              <td>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal_1" data-whatever="@mdo">回答する</button>
                 
                 <%= form_for(@comment) do |f| %>
                  <%= render 'shared/error_messages', object: f.object %>
                   
                   <div class="modal fade" id="exampleModal_1" tabindex="-1" role="dialog" aria-labelledby="exampleModal_1Label">
                    
                    <div class="modal-dialog" role="document">
                     
                     <div class="modal-content">
                      
                      <div class="modal-header">
                       <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="exampleModal_1Label">New message</h4>
                      </div>

                      <div class="modal-body">
                        <div class="form-group">
                          <label for="recipient-name" class="control-label">回答者</label>
                          <%= @user.name %>
                        </div>
          
                        <div class="form-group">
                         <label for="message-text" class="control-label">Message:</label>
                          <%= f.text_area :content, placeholder: "Compose new comment...", class: 'form-control', :size => "20x10" %>
                          <%= f.hidden_field :answer_id , :value => "@qalist.id" %>
                          <%= f.hidden_field :answer_td_id_1 , :value => "@qalist.line1" %>
                        </div>
                    
                      </div>
                    
                      <div class="modal-footer">
                       <%= f.submit "Post", class: "btn btn-primary" %>
                      </div>
                   
                    </div>
                    
                  </div>
                  
               </div>
              <% end %>
            </td>
              
            <td>
              <% if @answered_comments_1.any? %>
               <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal_1">Comments (<%= @answered_comments_1.count %>)</button>
                <div class="modal fade" id="myModal_1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                 <div class="modal-dialog" role="document">
                  <div class="modal-content">
                   <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                     <h4 class="modal-title" id="myModalLabel">コメント一覧</h4>
                   </div>
                    <div class="modal-body">
                     <ol class="comments">
                      <%= render partial: 'comments/comment', collection: @answered_comments_1 %>
                     </ol>
                    </div>
                     <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                     </div>
                  </div>
                 </div>
                </div>
              <% end %>
            </td>
            </tr>

app/views/qalists/_query2.html.erb
            <tr>
              <td><%= @qalist.query2 %></td>
              <td><%= @qalist.line2 %></td>
              <td></td>
              <td>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal_2" data-whatever="@mdo">回答する</button>
                 
                 <%= form_for(@comment) do |f| %>
                  <%= render 'shared/error_messages', object: f.object %>
                   
                   <div class="modal fade" id="exampleModal_2" tabindex="-1" role="dialog" aria-labelledby="exampleModal_2Label">
                    
                    <div class="modal-dialog" role="document">
                     
                     <div class="modal-content">
                      
                      <div class="modal-header">
                       <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="exampleModal_2Label">New message</h4>
                      </div>

                      <div class="modal-body">
                        <div class="form-group">
                          <label for="recipient-name" class="control-label">回答者</label>
                          <%= @user.name %>
                        </div>
          
                        <div class="form-group">
                         <label for="message-text" class="control-label">Message:</label>
                          <%= f.text_area :content, placeholder: "Compose new comment...", class: 'form-control', :size => "20x10" %>
                          <%= f.hidden_field :answer_id , :value => "@qalist.id" %>
                          <%= f.hidden_field :answer_td_id_2 , :value => "@qalist.line" %>
                        </div>
                    
                      </div>
                    
                      <div class="modal-footer">
                       <%= f.submit "Post", class: "btn btn-primary" %>
                      </div>
                   
                    </div>
                    
                  </div>
                  
               </div>
              <% end %>
            </td>
              
            <td>
              <% if @answered_comments_2.any? %>
               <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal_2">Comments (<%= @answered_comments_2.count %>)</button>
                <div class="modal fade" id="myModal_2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                 <div class="modal-dialog" role="document">
                  <div class="modal-content">
                   <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                     <h4 class="modal-title" id="myModalLabel">コメント一覧</h4>
                   </div>
                    <div class="modal-body">
                     <ol class="comments">
                      <%= render partial: 'comments/comment', collection: @answered_comments_2 %>
                     </ol>
                    </div>
                     <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                     </div>
                  </div>
                 </div>
                </div>
              <% end %>
            </td>
            </tr>

app/views/qalists/_query3.html.erb
            <tr>
              <td><%= @qalist.query3 %></td>
              <td><%= @qalist.line3 %></td>
              <td></td>
              <td>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal_3" data-whatever="@mdo">回答する</button>
                 
                 <%= form_for(@comment) do |f| %>
                  <%= render 'shared/error_messages', object: f.object %>
                   
                   <div class="modal fade" id="exampleModal_3" tabindex="-1" role="dialog" aria-labelledby="exampleModal_3Label">
                    
                    <div class="modal-dialog" role="document">
                     
                     <div class="modal-content">
                      
                      <div class="modal-header">
                       <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="exampleModal_3Label">New message</h4>
                      </div>

                      <div class="modal-body">
                        <div class="form-group">
                          <label for="recipient-name" class="control-label">回答者</label>
                          <%= @user.name %>
                        </div>
          
                        <div class="form-group">
                         <label for="message-text" class="control-label">Message:</label>
                          <%= f.text_area :content, placeholder: "Compose new comment...", class: 'form-control', :size => "20x10" %>
                          <%= f.hidden_field :answer_id , :value => "@qalist.id" %>
                          <%= f.hidden_field :answer_td_id_3 , :value => "@qalist.line3" %>
                        </div>
                    
                      </div>
                    
                      <div class="modal-footer">
                       <%= f.submit "Post", class: "btn btn-primary" %>
                      </div>
                   
                    </div>
                    
                  </div>
                  
               </div>
              <% end %>
            </td>
              
            <td>
              <% if @answered_comments_3.any? %>
               <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal_3">Comments (<%= @answered_comments_3.count %>)</button>
                <div class="modal fade" id="myModal_3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                 <div class="modal-dialog" role="document">
                  <div class="modal-content">
                   <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                     <h4 class="modal-title" id="myModalLabel">コメント一覧</h4>
                   </div>
                    <div class="modal-body">
                     <ol class="comments">
                      <%= render partial: 'comments/comment', collection: @answered_comments_3 %>
                     </ol>
                    </div>
                     <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                     </div>
                  </div>
                 </div>
                </div>
              <% end %>
            </td>
            </tr>

app/views/qalists/_query4.html.erb
            <tr>
              <td><%= @qalist.query4 %></td>
              <td><%= @qalist.line4 %></td>
              <td></td>
              <td>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal_4" data-whatever="@mdo">回答する</button>
                 
                 <%= form_for(@comment) do |f| %>
                  <%= render 'shared/error_messages', object: f.object %>
                   
                   <div class="modal fade" id="exampleModal_4" tabindex="-1" role="dialog" aria-labelledby="exampleModal_4Label">
                    
                    <div class="modal-dialog" role="document">
                     
                     <div class="modal-content">
                      
                      <div class="modal-header">
                       <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="exampleModal_4Label">New message</h4>
                      </div>

                      <div class="modal-body">
                        <div class="form-group">
                          <label for="recipient-name" class="control-label">回答者</label>
                          <%= @user.name %>
                        </div>
          
                        <div class="form-group">
                         <label for="message-text" class="control-label">Message:</label>
                          <%= f.text_area :content, placeholder: "Compose new comment...", class: 'form-control', :size => "20x10" %>
                          <%= f.hidden_field :answer_id , :value => "@qalist.id" %>
                          <%= f.hidden_field :answer_td_id_4 , :value => "@qalist.line4" %>
                        </div>
                    
                      </div>
                    
                      <div class="modal-footer">
                       <%= f.submit "Post", class: "btn btn-primary" %>
                      </div>
                   
                    </div>
                    
                  </div>
                  
               </div>
              <% end %>
            </td>
              
            <td>
              <% if @answered_comments_4.any? %>
               <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal_4">Comments (<%= @answered_comments_4.count %>)</button>
                <div class="modal fade" id="myModal_4" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                 <div class="modal-dialog" role="document">
                  <div class="modal-content">
                   <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                     <h4 class="modal-title" id="myModalLabel">コメント一覧</h4>
                   </div>
                    <div class="modal-body">
                     <ol class="comments">
                      <%= render partial: 'comments/comment', collection: @answered_comments_4 %>
                     </ol>
                    </div>
                     <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                     </div>
                  </div>
                 </div>
                </div>
              <% end %>
            </td>
            </tr>

app/views/qalists/_query5.html.erb
            <tr>
              <td><%= @qalist.query5 %></td>
              <td><%= @qalist.line5 %></td>
              <td></td>
              <td>
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal_5" data-whatever="@mdo">回答する</button>
                 
                 <%= form_for(@comment) do |f| %>
                  <%= render 'shared/error_messages', object: f.object %>
                   
                   <div class="modal fade" id="exampleModal_5" tabindex="-1" role="dialog" aria-labelledby="exampleModal_5Label">
                    
                    <div class="modal-dialog" role="document">
                     
                     <div class="modal-content">
                      
                      <div class="modal-header">
                       <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="exampleModal_5Label">New message</h4>
                      </div>

                      <div class="modal-body">
                        <div class="form-group">
                          <label for="recipient-name" class="control-label">回答者</label>
                          <%= @user.name %>
                        </div>
          
                        <div class="form-group">
                         <label for="message-text" class="control-label">Message:</label>
                          <%= f.text_area :content, placeholder: "Compose new comment...", class: 'form-control', :size => "20x10" %>
                          <%= f.hidden_field :answer_id , :value => "@qalist.id" %>
                          <%= f.hidden_field :answer_td_id_5 , :value => "@qalist.line5" %>
                        </div>
                    
                      </div>
                    
                      <div class="modal-footer">
                       <%= f.submit "Post", class: "btn btn-primary" %>
                      </div>
                   
                    </div>
                    
                  </div>
                  
               </div>
              <% end %>
            </td>
              
            <td>
              <% if @answered_comments_5.any? %>
               <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal_5">Comments (<%= @answered_comments_5.count %>)</button>
                <div class="modal fade" id="myModal_5" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                 <div class="modal-dialog" role="document">
                  <div class="modal-content">
                   <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                     <h4 class="modal-title" id="myModalLabel">コメント一覧</h4>
                   </div>
                    <div class="modal-body">
                     <ol class="comments">
                      <%= render partial: 'comments/comment', collection: @answered_comments_5 %>
                     </ol>
                    </div>
                     <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                     </div>
                  </div>
                 </div>
                </div>
              <% end %>
            </td>
            </tr>

app/views/qalists/show.html.erb
<div class="row">
  <aside class="col-md-6">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <%= link_to "マイページへ戻る", @user %>
    </section>
  </aside>
  <div class="col-md-12">
      <h3><%= @qalist.title %></h3>
       <h4>作成者<%= link_to @qalist.user.name, @qalist.user %></h4>
        <table class="table table-striped table-bordered table-hover">
           
          <tbody>
          　<tr>
               <th>質問</th>
               <th>期日</th>
               <th>状況</th>
               <th>コメントする</th>
               <th>コメントを見る</th>
            </tr>
            <% if @qalist.query0.present? %>
            <%= render 'qalists/query0', object: @qalist %>
        　　<% end %>
        　　<% if @qalist.query1.present? %>
            <%= render 'qalists/query1', object: @qalist %>
        　　<% end %>
        　　<% if @qalist.query2.present? %>
            <%= render 'qalists/query2', object: @qalist %>
        　　<% end %>
        　　<% if @qalist.query3.present? %>
            <%= render 'qalists/query3', object: @qalist %>
        　　<% end %>
        　　<% if @qalist.query4.present? %>
            <%= render 'qalists/query4', object: @qalist %>
        　　<% end %>
        　　<% if @qalist.query5.present? %>
            <%= render 'qalists/query5', object: @qalist %>
        　　<% end %>
        　　<% if @qalist.query6.present? %>
            <%= render 'qalists/query6', object: @qalist %>
        　　<% end %>
        　　<% if @qalist.query7.present? %>
            <%= render 'qalists/query7', object: @qalist %>
        　　<% end %>
        　　<% if @qalist.query8.present? %>
            <%= render 'qalists/query8', object: @qalist %>
        　　<% end %>
        　　<% if @qalist.query9.present? %>
            <%= render 'qalists/query9', object: @qalist %>
        　　<% end %>
           </tbody>
        </table>
        <% if current_user == @qalist.user %>
        <%= link_to "内容を変更する", edit_qalist_path %>
        <% end %>
   </div>
</div>